[tool.poetry]
name = "cvparser"
version = "0.1.0"
description = ""
authors = ["Amit <amit.kr.py@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
protobuf = ">=3.20,<5"
traits = ">=4.6,<5.0 || >5.0,<6.4"
ml-dtypes = ">=0.3.1,<0.4.0"
absl-py = "^2.1.0"
accelerate = "^0.30.1"
altair = "^5.3.0"
annotated-types = "^0.7.0"
anyio = "^4.4.0"
astunparse = "^1.6.3"
attrs = "^23.2.0"
blinker = "^1.8.2"
cachetools = "^5.3.3"
certifi = "^2024.2.2"
charset-normalizer = "^3.3.2"
ci-info = "^0.3.0"
click = "^8.1.7"
configobj = "^5.0.8"
configparser = "^7.0.0"
distro = "^1.9.0"
etelemetry = "^0.3.1"
exceptiongroup = "^1.2.1"
filelock = "^3.14.0"
fitz = "^0.0.1.dev2"
flatbuffers = "^24.3.25"
fsspec = "^2024.5.0"
gast = "^0.5.4"
gitdb = "^4.0.11"
gitpython = "^3.1.43"
google-pasta = "^0.2.0"
grpcio = "^1.64.0"
h11 = "^0.14.0"
h5py = "^3.11.0"
httpcore = "^1.0.5"
httplib2 = "^0.22.0"
httpx = "^0.27.0"
huggingface = "^0.0.1"
huggingface-hub = "^0.23.2"
idna = "^3.7"
isodate = "^0.6.1"
jinja2 = "^3.1.4"
joblib = "^1.4.2"
jsonschema = "^4.22.0"
jsonschema-specifications = "^2023.12.1"
keras = "^3.3.3"
libclang = "^18.1.1"
looseversion = "^1.3.0"
lxml = "^5.2.2"
markdown = "^3.6"
markdown-it-py = "^3.0.0"
markupsafe = "^2.1.5"
mdurl = "^0.1.2"
mpmath = "^1.3.0"
namex = "^0.0.8"
networkx = "^3.3"
nibabel = "^5.2.1"
nipype = "^1.8.6"
numpy = "^1.26.4"
openai = "^1.30.3"
opencv-python-headless = "^4.9.0.80"
opt-einsum = "^3.3.0"
optree = "^0.11.0"
packaging = "^24.0"
pandas = "^2.2.2"
pathlib = "^1.0.1"
pdf2image = "^1.17.0"
pillow = "^10.3.0"
prov = "^2.0.0"
psutil = "^5.9.8"
pyarrow = "^16.1.0"
pydantic = "^2.7.1"
pydantic-core = "^2.18.2"
pydeck = "^0.9.1"
pydot = "^2.0.0"
pygments = "^2.18.0"
pymupdf = "^1.24.4"
pymupdfb = "^1.24.3"
pyparsing = "^3.1.2"
pytesseract = "^0.3.10"
python-dateutil = "^2.9.0.post0"
python-docx = "^1.1.2"
pytz = "^2024.1"
pyxnat = "^1.6.2"
pyyaml = "^6.0.1"
rdflib = "^7.0.0"
referencing = "^0.35.1"
regex = "^2024.5.15"
requests = "^2.32.2"
rich = "^13.7.1"
rpds-py = "^0.18.1"
safetensors = "^0.4.3"
scikit-learn = "^1.5.0"
scipy = "^1.13.1"
sentence-transformers = "^3.0.0"
simplejson = "^3.19.2"
six = "^1.16.0"
smmap = "^5.0.1"
sniffio = "^1.3.1"
streamlit = "^1.35.0"
sympy = "^1.12"
tenacity = "^8.3.0"
tensorboard = "^2.16.2"
tensorboard-data-server = "^0.7.2"
tensorflow = "^2.16.1"
tensorflow-io-gcs-filesystem = "^0.37.0"
#tensorflow-metal = "^1.1.0"
termcolor = "^2.4.0"
tf-keras = "^2.16.0"
threadpoolctl = "^3.5.0"
tokenizer = "^3.4.3"
tokenizers = "^0.19.1"
toml = "^0.10.2"
toolz = "^0.12.1"
torch = "^2.3.0"
torchaudio = "^2.3.0"
torchvision = "^0.18.0"
tornado = "^6.4"
tqdm = "^4.66.4"
transformers = "^4.41.1"
typing-extensions = "^4.12.0"
tzdata = "^2024.1"
urllib3 = "^2.2.1"
werkzeug = "^3.0.3"
wrapt = "^1.16.0"
docx2pdf = "^0.1.8"
poppler-utils = "^0.1.0"
easyocr = "^1.7.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
